---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : yaotian
production_url : http://zhengyaotian.com

posts:
  permalink: /:categories/:title/
  summary_lines: 30
  latest: 30

pages:
  permalink: 'pretty'

# <img> tag auto insert config
# %s will be replace by "urlperfix / post name / img filename"
imgs:
  imgtag: '<img src="%s" alt="" width="600">'
  urlperfix: '{{urls.media}}/'
  localdir: 'media/'



